=== dedis/popstellar/protocol/query/method/message/data/dataFederationInit.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/message/data/dataFederationInit.json",
    "description": "Sent by an organizer client to its server, initiates a connection to a remote LAO",
    "type": "object",
    "properties": {
        "object": {
            "const": "federation"
        },
        "action": {
            "const": "init"
        },
        "lao_id": {
            "type": "string",
            "contentEncoding": "base64",
            "$comment": "ID of the remote LAO"
        },
        "server_address": {
            "type": "string",
            "pattern": "^(ws|wss):\/\/.*(:\\d{0,5})?\/.*$",
            "$comment": "public address of the remote organizer server"
        },
        "public_key": {
            "type": "string",
            "contentEncoding": "base64",
            "$comment": "public key of the remote organizer"
        },
        "challenge": {
            "$ref": "../message.json",
            "$comment": "message/message containing a FederationChallenge data"
        }
    },
    "additionalProperties": false,
    "required": [
        "object",
        "action",
        "lao_id",
        "server_address",
        "public_key",
        "challenge"
    ]
}

=== dedis/popstellar/protocol/examples/messageData/federation_init/federation_init.json
{
    "object": "federation",
    "action": "init",
    "lao_id": "fzJSZjKf-2cbXH7kds9H8NORuuFIRLkevJlN7qQemjo=",
    "public_key": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
    "server_address": "wss://epfl.ch:9000/server",
    "challenge": "ewogICAgICAgICJEYXRhIjogImV5SnZZbXBsWTNRaU9pSm1aV1JsY21GMGFXOXVJaXdpWVdOMGFXOXVJam9pWTJoaGJHeGxibWRsSWl3aWRtRnNkV1VpT2lKbFltRXpaVEkwWldaalpEQmlOVE5tWVRZNU9UQTRZbUZrTldReFkySTJPVGxrTnprNE1HUTVNekV3T1dSaE1HSXlZbVprTlRBek4yTXlZemc1WldVd0lpd2lkR2x0WlhOMFlXMXdJam94TnpFek16ZzFOVFk0ZlE9PSIsCiAgICAgICAgIlNlbmRlciI6ICJ6WGd6UWFhX05wVWUtdjBaa180cThrMTg0b2hRNW5UUWhCREtnbmNIenE0PSIsCiAgICAgICAgIlNpZ25hdHVyZSI6ICJCSUxZd1lrVDV0T0JMNHJDRDd5dmhCa2hBWXFSWE9JM2FqUTJ1SjFnQWstZzZuUmMzOHZNTW5sSFNodU5DUTNkUUZYWVpQbjM3Y0NGZWxoV0dqWThCZz09IiwKICAgICAgICAiTWVzc2FnZUlEIjogInNEX1BkcnlCdU9yMTRfNjVoOEwtZTFsemRRcERXeFVBbmd0dTF1d3FnRUk9IiwKICAgICAgICAiV2l0bmVzc1NpZ25hdHVyZXMiOiBbXQogICAgfQ=="
}
