=== dedis/popstellar/protocol/query/method/message/data/dataCastVote.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/student_21_pop/master/protocol/query/method/message/data/dataCastVote.json",
    "description": "Match a cast vote query",
    "type": "object",
    "properties": {
        "object": {
            "const": "election"
        },
        "action": {
            "const": "cast_vote"
        },
        "lao": {
            "type": "string",
            "contentEncoding": "base64",
            "$comment": "ID of the LAO"
        },
        "election": {
            "type": "string",
            "contentEncoding": "base64",
            "$comment": "ID of the election"
        },
        "created_at": {
            "description": "[Timestamp] time created in UTC",
            "type": "integer",
            "minimum": 0
        },
        "votes": {
            "description": "Array of votes",
            "type": "array",
            "items": {
                "type": "object",
                "allOf": [
                    {
                        "properties": {
                            "id": {
                                "type": "string",
                                "contentEncoding": "base64",
                                "$comment": "Hash : HashLen('Vote', election_id, question_id, (vote_index(es)|write_in)), concatenate vote indexes - must use delimiter"
                            },
                            "question": {
                                "type": "string",
                                "contentEncoding": "base64",
                                "$comment": "ID of the question"
                            }
                        },
                        "required": ["id", "question"]
                    },
                    {
                        "oneOf": [
                            {
                                "properties": {
                                    "vote": {
                                        "description": "[Array[Integer]] index(es) corresponding to the ballot_options",
                                        "type": "array",
                                        "items": {
                                            "type": "integer",
                                            "$comment": "vote index"
                                        },
                                        "minItems": 1,
                                        "uniqueItems": true
                                    }
                                },
                                "required": ["vote"]
                            },
                            {
                                "properties": {
                                    "write_in": {
                                        "type": "string"
                                    }
                                },
                                "required": ["write_in"]
                            }
                        ]
                    }
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "additionalProperties": false,
    "required": ["object", "action", "lao", "election", "created_at", "votes"]
}

=== dedis/popstellar/protocol/examples/messageData/vote_cast_vote.json
{
    "object": "election",
    "action": "cast_vote",
    "lao": "fzJSZjKf-2cbXH7kds9H8NORuuFIRLkevJlN7qQemjo=",
    "election": "JVehtpaFJwPc2dp8VuiskXwxmjTQGT6OiIVbei-EbBI=",
    "created_at": 1633098941,
    "votes": [
        {
            "id": "JF8pLNhK6BArJpZxL7IWhbC6doPDpGPClRkgav0ry_0=",
            "question": "AQy6JrPiLXG7oIZ_EL83hbs87w_vjn5ZS3r4je1wV8o=",
            "vote": [0]
        }
    ]
}

=== dedis/popstellar/protocol/examples/messageData/vote_cast_write_in.json
{
    "object": "election",
    "action": "cast_vote",
    "lao": "fzJSZjKf-2cbXH7kds9H8NORuuFIRLkevJlN7qQemjo=",
    "election": "QWTmcWMMMiUdWdZX7ib7GyqH6A5ifDYwPaMpKxIZm1k=",
    "created_at": 1633098996,
    "votes": [
        {
            "id": "DtIsj7nQ0Y4iLJ4ETKv2D0uah7IYGyEVW7aCLFjaL0w=",
            "question": "WBVsWJI-C5YkD0wdE4DxnLa0lJzjnHEd67XPFVB9v3g=",
            "write_in": "Computer Science"
        }
    ]
}

=== dedis/popstellar/tests/karate/src/test/java/data/election/data/castVote/valid_cast_vote_2_data.json
{
  "object": "election",
  "action": "cast_vote",
  "lao": "p_EYbHyMv6sopI5QhEXBf40MO_eNoq7V_LygBd4c9RA=",
  "election": "rdv-0minecREM9XidNxnQotO7nxtVVnx-Zkmfm7hm2w=",
  "created_at": 1633098941,
  "votes": [
    {
      "id": "d60B94lVWm84lBHc9RE5H67oH-Ad3O1WFflK3NSY3Yk=",
      "question": "3iPxJkdUiCgBd0c699KA9tU5U0zNIFau6spXs5Kw6Pg=",
      "vote": [0]
    }
  ]
}
