=== dedis/popstellar/protocol/query/method/message/data/dataLearn.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/student_21_pop/master/protocol/query/method/message/data/dataLearn.json",
    "description": "Match a learn query",
    "type": "object",
    "properties": {
        "object": {
            "const": "consensus"
        },
        "action": {
            "const": "learn"
        },
        "message_id": {
            "description": "message_id of the elect message",
            "type": "string"
        },
        "acceptors": {
            "description": "Array of the message_ids of the elect-accept messages that accepted this proposal",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "object",
        "action",
        "message_id",
        "acceptors"
    ]
}

=== dedis/popstellar/protocol/examples/messageData/learn.json
{
    "object": "consensus",
    "action": "learn",
    "message_id": "6z1k9Eqet9-YAOdEE9NaIQMvw8_W_Fj-u2vRL4siIb0=",
    "acceptors": [
        "pFFLRiOVyFX2UwFw8kd8PnVg6rshT-ofWYVAc_QuRz4=",
        "cSaSHaZzvVR_sfcD5xngSxafK1eCDxmrd0d1C7-VHXJ=",
        "OtP_nVgrshTofWYVAcQ-uRz44UD_2tFJUOLLvTbFmzO="
    ]
}
