=== dedis/popstellar/protocol/query/method/message/data/dataElectionSetup.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/dedis/student_21_pop/master/protocol/query/method/message/data/dataSetupElection.json",
	"description": "Match an ElectionSetup query",
	"type": "object",

	"properties": {
		"object": { "const": "election" },
		"action": { "const": "setup" },
		"id": {
			"type": "string",
			"contentEncoding": "base64",
			"$comment": "Hash : SHA256('Election'||lao_id||created_at||name)"
		},
		"lao": { 
			"type": "string",
			"contentEncoding": "base64",
			"$comment": "ID of the LAO"
			},
		"name": { 
			"type": "string",
			"$comment": "name of the election"
		},
		"version": { 
			"type": "string",
			"$comment": "features/implementation identifier"
		},
		"created_at": {
			"description": "[Timestamp] time created in UTC",
			"type": "integer",
			"minimum": 0
		},
		"start_time": {
			"description": "[Timestamp] start time of the election in UTC",
			"type": "integer",
			"minimum": 0
		},
		"end_time": {
			"description": "[Timestamp] end time of the election in UTC",
			"type": "integer",
			"minimum": 0
		},
		"questions": {
			"description": "Array of questions",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"contentEncoding": "base64",
						"$comment": "ID of the question"
					},
					"question": {
						"type": "string",
						"$comment": "voting topic"
					},
					"voting_method": {
						"type": "string",
						"enum": ["Plurality", "Approval"],
						"$comment": "supported voting method"
					},
					"ballot_options": {
						"description": "[Array[String]] ballot options",
						"type": "array",
						"items": {
							"type": "string",
							"$comment": "ballot option"
						},
						"minItems": 1,
						"uniqueItems": true
					},
					"write_in": {
						"type": "boolean",
						"$comment": "whether write-in is allowed"
					}
				},
				"additionalProperties": false,
				"required": ["id", "question", "voting_method", "ballot_options", "write_in"]
			},
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"additionalProperties": false,
	"required": ["object", "action", "id", "lao", "name", "version", "created_at", "start_time", "end_time", "questions"]
}

=== dedis/popstellar/tests/karate/src/test/java/data/election/data/electionSetup/valid_election_setup_2_data.json
{
  "object": "election",
  "action": "setup",
  "id": "ZVxXK2QN60uCNxNsIzShYYQmtwGttWLpQPQapYCNg4g=",
  "lao": "p_EYbHyMv6sopI5QhEXBf40MO_eNoq7V_LygBd4c9RA=",
  "name": "NewElection",
  "version": "1.0.0",
  "created_at": 1633098941,
  "start_time": 1633098941,
  "end_time": 1633099812,
  "questions": [
    {
      "id": "k0RvqQHCELFjr2RxgUWRmq2tDb6koGs2MhYr5D5PAoU=",
      "question": "Where to go out?",
      "voting_method": "Plurality",
      "ballot_options": ["Bar", "Club", "Restaurant"],
      "write_in": false
    }
  ]
}
