=== dedis/popstellar/be1-go/internal/validation/protocol/query/method/message/data/dataPostTransactionCoin.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/message/data/dataPostTransactionCoin.json",
  "title": "Post a digital cash transaction",
  "type": "object",
  "properties": {
    "object": {
      "const": "coin"
    },
    "action": {
      "const": "post_transaction"
    },
	"transaction_id": {
        "type": "string",
        "contentEncoding": "base64",
        "description": "SHA 256 Hash over base64 of transaction - must be verified"
    },
    "transaction": {
      "type": "object",
      "description": "The transaction object",
      "properties": {
        "version": {
          "type": "integer",
          "description": "The version of the transaction inputs"
        },
        "inputs": {
          "type": "array",
          "description": "[Array[Objects]] array of output transactions to use as inputs",
          "items": {
            "type": "object",
            "description": "Object representing a transaction output to use as an input for this transaction",
            "properties": {
              "tx_out_hash": {
                "type": "string",
                "contentEncoding": "base64",
                "description": "Previous (to-be-used) transaction hash"
              },
              "tx_out_index": {
                "type": "integer",
                "description": "Index of the previous to-be-used transaction"
              },
              "script": {
                "type": "object",
                "description": "The script describing the unlock mechanism",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "Type of script"
                  },
                  "pubkey": {
                    "type": "string",
                    "contentEncoding": "base64",
                    "description": "The recipient’s public key"
                  },
                  "sig": {
                    "type": "string",
                    "contentEncoding": "base64",
                    "description": "Signature on all txins and txouts using the recipient's private key"
                  }
                },
                "required": ["type", "pubkey", "sig"]
              }
            },
            "required": ["tx_out_hash", "tx_out_index", "script"]
          },
          "minItems": 1
        },
        "outputs": {
          "type": "array",
          "description": "[Array[Objects]] array of outputs from this transactions",
          "items": {
            "type": "object",
            "description": "Object representing an output of this transaction",
            "properties": {
              "value": {
                "type": "integer",
                "minimum": 0,
                "maximum": 9007199254740991,
                "description": "the value of the output transaction, expressed in miniLAOs"
              },
              "script": {
                "type": "object",
                "description": "The script describing the TxOut unlock mechanism",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "Type of script"
                  },
                  "pubkey_hash": {
                    "type": "string",
                    "contentEncoding": "base64",
                    "description": "Hash of the recipient’s public key"
                  }
                },
                "required": ["type", "pubkey_hash"]
              }
            },
            "required": ["value", "script"]
          },
          "minItems": 1
        },
        "lock_time": {
          "type": "integer",
          "description": "Timestamp"
        }
      },
      "required": ["version", "inputs", "outputs", "lock_time"]
    }
  },
  "required": ["object", "action", "transaction_id", "transaction"]
}

=== dedis/popstellar/protocol/examples/messageData/coin/post_transaction_max_amount.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "K6GbqfHbCxLaihkDI88BEobHYNRKqYpASXp1QNSXPOo=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "47DEQpj8HBSa--TImW-5JCeuQeRkm5NMpJWZG3hSuFU=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			    "sig": "CAFEBABE"
		    }
	    }],
	    "outputs": [{
		    "value": 9007199254740991,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "2jmj7l5rSw0yVb-vlWAYkK-YBwk="
		    }
	    }],
	    "lock_time": 0
    }
}

=== dedis/popstellar/be1-go/internal/validation/protocol/examples/messageData/coin/post_transaction_zero_amount.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "J4WK2mwS_hiBPxQLS6ujZ6WGXGg0ghBVZoZ0qB0NcoU=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "01N1Y8twdu7wpdz5HLnkIeQSeuKpkNcQHeKF7XabLYU=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "oKHk3AivbpNXk_SfFcHDaVHcCcY8IBfHE7auXJ7h4ms=",
			    "sig": "VcQ6RheWuDHNoXWSL2SZbMcOHJtSQ5Cwl7iho0p3ck-MoARUy3m_bidwXv7VOX4uxJu3J_SMlopPGgN47teSCA=="
		    }
	    }],
	    "outputs": [{
		    "value": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "2jmj7l5rSw0yVb-vlWAYkK-YBwk="
		    }
	    }],
	    "lock_time": 0
    }
}

=== dedis/popstellar/be1-go/internal/validation/protocol/examples/messageData/coin/post_transaction_overflow_sum.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "Mfb8JwEb0rn6lZe9m6TJBRtleGMxnaF5HUfy6QJt7ac=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "47DEQpj8HBSa--TImW-5JCeuQeRkm5NMpJWZG3hSuFU=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
			    "sig": "4SbbszRmoI4-Rlhs1q7-2Dge1o1pSNW5SPMcnZPPRNUfGZ3Dy60sHIfTcw3SC2T2v-Gp4oGiIeZvrvEFEKbjDA=="
		    }
	    }],
	    "outputs": [{
		    "value": 9007199254740991,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "2jmj7l5rSw0yVb-vlWAYkK-YBwk="
		    }
	    },
	    {
		    "value": 1,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "2jmj7l5rSw0yVb-vlWAYkK-YBwk="
		    }
	    }],
	    "lock_time": 0
    }
}

=== dedis/popstellar/be1-go/internal/validation/protocol/examples/messageData/coin/post_transaction.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "ESQimXKtIrt85EMSsmGoQ2kE2y1-ae6SAvp52Xp3KOQ=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "01N1Y8twdu7wpdz5HLnkIeQSeuKpkNcQHeKF7XabLYU=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "oKHk3AivbpNXk_SfFcHDaVHcCcY8IBfHE7auXJ7h4ms=",
			    "sig": "6hY16bDKnb7bRA5j7IMDR1CJDqAJKOLuQRgKxdpYQIrtSTVTRjo5jigqPhYQEPcK5a1WAF86V739ENFnlp6YCw=="
		    }
	    }],
	    "outputs": [{
		    "value": 32,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "-_qR4IHwsiq50raa8jURNArds54="
		    }
	    }],
	    "lock_time": 0
    }
}

=== dedis/popstellar/protocol/examples/messageData/coin/post_transaction_nooutput.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "47DEQpj8HBSa--TImW-5JCeuQeRkm5NMpJWZG3hSuFU=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "47DEQpj8HBSa--TImW-5JCeuQeRkm5NMpJWZG3hSuFU=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			    "sig": "CAFEBABE"
		    }
	    }],
	    "outputs": [],
	    "lock_time": 0
    }
}

=== dedis/popstellar/protocol/examples/messageData/coin/post_transaction_coinbase.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "zxNUqE_8PFK-Yb8LmXWtm4ZX0Mo6QsC3ugtg-9kRf4w=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		    "tx_out_index": 0,  
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			    "sig": "CAFEBABE"
			}
		}],
	    "outputs": [{
		    "value": 32,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "2jmj7l5rSw0yVb-vlWAYkK-YBwk="
			}
		}],
	    "lock_time": 0
	}
}

=== dedis/popstellar/be1-go/internal/validation/protocol/examples/messageData/coin/post_transaction_multipleinpandout.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "JhHsVj7gqXX9jhfV56AYq1ATnWEPKHC6JAHN6J9k8i4=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			    "sig": "CAFEBABE"
		    }
          },
            {
		    "tx_out_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			    "sig": "CAFEBABE"
		    }
        }],
	    "outputs": [{
		    "value": 32,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
		    }
	    },
                 {
		    "value": 32,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
		    }
	    }],
	    "lock_time": 0
    }
}

=== dedis/popstellar/be1-go/internal/validation/protocol/examples/messageData/coin/post_transaction_coinbase.json
{
    "object": "coin",
    "action": "post_transaction",
    "transaction_id": "oNtxrBVZaqA-6mNEEnqqSXWJMD5RGrdZBKfdkbbINLM=",
    "transaction": {
	    "version": 1,
	    "inputs": [{
		    "tx_out_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		    "tx_out_index": 0,
		    "script": {
			    "type": "P2PKH",
			    "pubkey": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
			    "sig": "GmDtDAEQTlfSnlKAYrySIlDFpxte-5wUfPeyCFgPkHQ-A7s0-RbEfabD8vTbNwDRVhVpbwr_shlULSWpmmlWBg=="
		    }
	    }],
	    "outputs": [{
		    "value": 32,
		    "script": {
			    "type": "P2PKH",
			    "pubkey_hash": "SGnNfF533PBEUMYPMqBSQY83z5U="
		    }
	    }],
	    "lock_time": 0
    }
}
