=== dedis/popstellar/be1-go/internal/validation/protocol/query/method/message/data/dataResultElection.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/message/data/dataResultElection.json",
    "description": "Match an ElectionResult query",
    "type": "object",
    "properties": {
        "object": {
            "const": "election"
        },
        "action": {
            "const": "result"
        },
        "questions": {
            "description": "Array of questions with their result",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "$comment": "ID of the question"
                    },
                    "result": {
                        "description": "[Array[object{'ballot_options':string, 'count':integer}]] results",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "$comment": "result of Plurality Voting",
                            "properties": {
                                "ballot_option": {
                                    "type": "string",
                                    "$comment": "string containing ballot option of the question"
                                },
                                "count": {
                                    "type": "integer",
                                    "$comment": "vote-count of the corresponding option",
                                    "minimum": 0
                                }
                            },
                            "required": ["ballot_option", "count"],
                            "additionalProperties": false
                        },
                        "minItems": 1,
                        "uniqueItems": true
                    }
                },
                "additionalProperties": false,
                "required": ["id", "result"]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "witness_signatures": {
            "description": "[Array[Base64String]] list of witnesses' signatures",
            "type": "array"
        }
    },
    "additionalProperties": false,
    "required": ["object", "action", "questions"]
}

=== dedis/popstellar/be1-go/internal/validation/protocol/examples/messageData/election_result.json
{
    "object": "election",
    "action": "result",
    "questions": [
        {
            "id": "2PLwVvqxMqW5hQJXkFpNCvBI9MZwuN8rf66V1hS-iZU=",
            "result": [
                {
                    "ballot_option": "Yes",
                    "count": 1
                },
                {
                    "ballot_option": "No",
                    "count": 0
                }
            ]
        }
    ],
    "witness_signatures": []
}
