=== dedis/popstellar/protocol/query/method/rumor_state.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/rumor_state.json",
    "description": "Match sharing state of last rumor seen per sender",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "method": {
            "description": "[String] operation to be performed by the query",
            "const": "rumor_state"
        },

        "params": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "rumor_state": {
                    "$ref": "object/rumor_state.json"
                }
            },
            "required": ["rumor_state"]
        },

        "jsonrpc": {
            "$comment": "Defined by the parent, but needed here for the validation"
        },

        "id": {
            "type": "integer"
        }
    },

    "required": ["method", "params", "id", "jsonrpc"]
}

=== dedis/popstellar/protocol/examples/query/rumor_state/rumor_state.json
{
    "jsonrpc": "2.0",
    "id": 4,
    "method": "rumor_state",
    "params": {
        "rumor_state": {
            "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=": 3,
            "RZOPi59Iy5gkpS2mkpfQJNl44HKc2jVbF0iTGm0RvfU=": 5,
            "CfG2ByLhtLJH--T2BL9hZ6eGm11tpkE-5KuvysSCY0I=": 1,
            "r8cG9HyJ1FGBke_5IblCdH19mvy39MvLFSArVmY3FpY=": 10
        }
    }
}
