=== dedis/popstellar/protocol/query/method/rumor.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/rumor.json",
    "description": "Rumor that should be spread across the network",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "method": {
            "description": "[String] operation to be performed by the query",
            "const": "rumor"
        },

        "params": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sender_id": {
                    "description": "[String] publish key of the sender's server",
                    "type": "string",
                    "contentEncoding": "base64"
                },
                "rumor_id": {
                    "description": "[Integer] ID of the rumor",
                    "type": "integer"
                },
                "messages": {
                    "description": "Key-value of channels and messages per channel",
                    "type": "object",
                    "$ref": "../../answer/result/messages_by_channel.json"
                }
            },
            "required": ["sender_id", "rumor_id", "messages"]
        },

        "jsonrpc": {
            "$comment": "Defined by the parent, but needed here for the validation"
        },

        "id": {
            "type": "integer"
        }
    },

    "required": ["method", "params", "id", "jsonrpc"]
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/rumor/rumor_correct_msg_create_rollcall.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "rumor",
  "params": {
    "sender_id" : "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
    "rumor_id" : 1,
    "messages" : {
      "/root/ceHTqZJb51sgryoxygl-nwuMQLWF3xQ_W29fclqvwis=": [
        {
          "data": "eyJvYmplY3QiOiJtZWV0aW5nIiwiYWN0aW9uIjoiY3JlYXRlIiwibmFtZSI6Im5ldyBtZWV0aW5nIiwiY3JlYXRpb24iOjE3MTUxMTI4MDEsImxvY2F0aW9uIjoiQkM0MTAiLCJzdGFydCI6MTcxNTExMjgwMSwiZW5kIjoxNzE1MTE2Mzg5LCJpZCI6IjFBSzJ6NXFQdi1BZGliMjNYeDhzckRVUnQtckw1RzBiRXg3cV9Od1RRU1E9In0=",
          "message_id": "xTraLPJgPXpUYNG0h0gzNOBSUDI7oebqCtzJDYHD0FE=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "9vZBJMzeGQ93Wc6bXB6AUHC5O8yb1dKXkX-OvP9blM_f3Q_HpEtqNiw9Xf-tjkt3yPlq1s3bmK06ar8fEL4kCw==",
          "witness_signatures": []
        },
        {
          "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoibmV3Um9sbENhbGwiLCJjcmVhdGlvbiI6MTcxNTExMzEyNCwicHJvcG9zZWRfc3RhcnQiOjE3MTUxMTMxMjQsInByb3Bvc2VkX2VuZCI6MTcxNTExNjY2OSwibG9jYXRpb24iOiJCQzQxMCIsImRlc2NyaXB0aW9uIjoibmV3IHJvbGwgY2FsbCIsImlkIjoiSmJCZk1ManAwU0tGRlh4YzZNdTVxUVdWNzFPR0lBMEhDa3E5bUwyeThDND0ifQ==",
          "message_id": "L9yYdabmrnGYV56-HZSfzE_Vw8MNP2DKITyhgSbXu04=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "Dgg9TzFBVrMUYx71ysWZxPDtimw8TEhYBPAsyZU4FWwyUY8vfOmr-MraNKAUj2XDTbm0TijkzEGo2aVx1JZdAg==",
          "witness_signatures": []
        }
      ],
      "/root": [
        {
          "data": "eyJvYmplY3QiOiJsYW8iLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoibmV3T3JnIiwiY3JlYXRpb24iOjE3MTUxMTI3NTUsIm9yZ2FuaXplciI6InpzZEZTUEJnY29oZzE3d2lSbTNWSjZGQUUxVUhqN2VsMnhURDEtTWtnSE09Iiwid2l0bmVzc2VzIjpbXSwiaWQiOiJjZUhUcVpKYjUxc2dyeW94eWdsLW53dU1RTFdGM3hRX1cyOWZjbHF2d2lzPSJ9",
          "message_id": "NLsLn_VwL9zBqCOZC131OlS_xh0xwGt8KiJXpFZGftk=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "JEQubIvBJCpoADClMey3X8zd8NpRmUK5qDeARYORW9yv9G09k22I4ACBk_zW_QJis9kxxWcaUtHgEsi9YffoDg==",
          "witness_signatures": []
        }
      ]
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/rumor/rumor_correct_msg_close_rollcall.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "rumor",
  "params": {
    "sender_id" : "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
    "rumor_id" : 1,
    "messages" : {
      "/root/ceHTqZJb51sgryoxygl-nwuMQLWF3xQ_W29fclqvwis=": [
        {
          "data": "eyJvYmplY3QiOiJtZWV0aW5nIiwiYWN0aW9uIjoiY3JlYXRlIiwibmFtZSI6Im5ldyBtZWV0aW5nIiwiY3JlYXRpb24iOjE3MTUxMTI4MDEsImxvY2F0aW9uIjoiQkM0MTAiLCJzdGFydCI6MTcxNTExMjgwMSwiZW5kIjoxNzE1MTE2Mzg5LCJpZCI6IjFBSzJ6NXFQdi1BZGliMjNYeDhzckRVUnQtckw1RzBiRXg3cV9Od1RRU1E9In0=",
          "message_id": "xTraLPJgPXpUYNG0h0gzNOBSUDI7oebqCtzJDYHD0FE=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "9vZBJMzeGQ93Wc6bXB6AUHC5O8yb1dKXkX-OvP9blM_f3Q_HpEtqNiw9Xf-tjkt3yPlq1s3bmK06ar8fEL4kCw==",
          "witness_signatures": []
        },
        {
          "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoibmV3Um9sbENhbGwiLCJjcmVhdGlvbiI6MTcxNTExMzEyNCwicHJvcG9zZWRfc3RhcnQiOjE3MTUxMTMxMjQsInByb3Bvc2VkX2VuZCI6MTcxNTExNjY2OSwibG9jYXRpb24iOiJCQzQxMCIsImRlc2NyaXB0aW9uIjoibmV3IHJvbGwgY2FsbCIsImlkIjoiSmJCZk1ManAwU0tGRlh4YzZNdTVxUVdWNzFPR0lBMEhDa3E5bUwyeThDND0ifQ==",
          "message_id": "L9yYdabmrnGYV56-HZSfzE_Vw8MNP2DKITyhgSbXu04=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "Dgg9TzFBVrMUYx71ysWZxPDtimw8TEhYBPAsyZU4FWwyUY8vfOmr-MraNKAUj2XDTbm0TijkzEGo2aVx1JZdAg==",
          "witness_signatures": []
        },
        {
          "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJvcGVuIiwib3BlbmVkX2F0IjoxNzE1MTEzMzAyLCJvcGVucyI6IkpiQmZNTGpwMFNLRkZYeGM2TXU1cVFXVjcxT0dJQTBIQ2txOW1MMnk4QzQ9IiwidXBkYXRlX2lkIjoiWHh3dXVXVkdwWU9wNS11UW9reTUxZG14OG1RWUk2d2RvdmZDd244UVJlRT0ifQ==",
          "message_id": "miYL90H_F8Ts9SI3lKWR6b1iaLewChdydNCkuLeS1uM=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "v-IaxM6O_ibOK_YLJWdn9iRVV3SvABxE21PsWHsmA6LrbieZeIwBgiypImwiYolzAK1N7Km2fg2BjzXNiU39Aw==",
          "witness_signatures": []
        },
        {
          "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjbG9zZSIsImNsb3NlZF9hdCI6MTcxNTExMzQ0MCwiYXR0ZW5kZWVzIjpbImxQUUxidE81UllVclNXSjY2WkxLdkl1M2JLbll1ZmR2WHBxNXdianJGRDg9Il0sImNsb3NlcyI6Ilh4d3V1V1ZHcFlPcDUtdVFva3k1MWRteDhtUVlJNndkb3ZmQ3duOFFSZUU9IiwidXBkYXRlX2lkIjoibk9CZktGdHJJS21LbmQyb0UwSTY0LU9waGNzQnp5R1NpNThJMHZnQzJwZz0ifQ==",
          "message_id": "vbtKFXIjvmdKvrm3JO9LCVO_UWYmYEm9cko-mnAM__k=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "SagjK-ZU1LnHruwmBPZ0kvHzbFMef5Klr8Hbqrml-rm-OApWYbex3WRmEXohNt6RoLxPN3Xdy5LlSfsrRFbNBw==",
          "witness_signatures": []
        }
      ],
      "/root": [
        {
          "data": "eyJvYmplY3QiOiJsYW8iLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoibmV3T3JnIiwiY3JlYXRpb24iOjE3MTUxMTI3NTUsIm9yZ2FuaXplciI6InpzZEZTUEJnY29oZzE3d2lSbTNWSjZGQUUxVUhqN2VsMnhURDEtTWtnSE09Iiwid2l0bmVzc2VzIjpbXSwiaWQiOiJjZUhUcVpKYjUxc2dyeW94eWdsLW53dU1RTFdGM3hRX1cyOWZjbHF2d2lzPSJ9",
          "message_id": "NLsLn_VwL9zBqCOZC131OlS_xh0xwGt8KiJXpFZGftk=",
          "sender": "zsdFSPBgcohg17wiRm3VJ6FAE1UHj7el2xTD1-MkgHM=",
          "signature": "JEQubIvBJCpoADClMey3X8zd8NpRmUK5qDeARYORW9yv9G09k22I4ACBk_zW_QJis9kxxWcaUtHgEsi9YffoDg==",
          "witness_signatures": []
        }
      ]
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/rumor/rumor.json
{
    "jsonrpc": "2.0",
    "id": 4,
    "method": "rumor",
    "params": {
        "sender_id": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
        "rumor_id": 0,
        "messages": {
            "/root/nLghr9_P406lfkMjaNWqyohLxOiGlQee8zad4qAfj18=/social/8qlv4aUT5-tBodKp4RszY284CFYVaoDZK6XKiw9isSw=": [
                {
                    "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoiUm9sbCBDYWxsIiwiY3JlYXRpb24iOjE2MzMwMzYxMjAsInByb3Bvc2VkX3N0YXJ0IjoxNjMzMDM2Mzg4LCJwcm9wb3NlZF9lbmQiOjE2MzMwMzk2ODgsImxvY2F0aW9uIjoiRVBGTCIsImlkIjoial9kSmhZYnpubXZNYnVMc0ZNQ2dzYlB5YjJ6Nm1vZ2VtSmFON1NWaHVVTT0ifQ==",
                    "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
                    "signature": "FFqBXhZSaKvBnTvrDNIeEYMpFKI5oIa5SAewquxIBHTTEyTIDnUgmvkwgccV9NrujPwDnRt1f4CIEqzXqhbjCw==",
                    "message_id": "DCBX48EuNO6q-Sr42ONqsj7opKiNeXyRzrjqTbZ_aMI=",
                    "witness_signatures": []
                }
            ],
            "/root/nLghr9_P406lfkMjaNWqyohLxOiGlQee8zad4qAfj18=/HnXDyvSSron676Icmvcjk5zXvGLkPJ1fVOaWOxItzBE=": [
                {
                    "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoiUm9sbCBDYWxsIiwiY3JlYXRpb24iOjE2MzMwMzYxMjAsInByb3Bvc2VkX3N0YXJ0IjoxNjMzMDM2Mzg4LCJwcm9wb3NlZF9lbmQiOjE2MzMwMzk2ODgsImxvY2F0aW9uIjoiRVBGTCIsImlkIjoial9kSmhZYnpubXZNYnVMc0ZNQ2dzYlB5YjJ6Nm1vZ2VtSmFON1NWaHVVTT0ifQ==",
                    "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
                    "signature": "FFqBXhZSaKvBnTvrDNIeEYMpFKI5oIa5SAewquxIBHTTEyTIDnUgmvkwgccV9NrujPwDnRt1f4CIEqzXqhbjCw==",
                    "message_id": "z6SbjJ0Hw36k8L09-GVRq4PNmi06yQX4e8aZRSbUDwc=",
                    "witness_signatures": []
                },
                {
                    "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoiUm9sbCBDYWxsIiwiY3JlYXRpb24iOjE2MzMwMzYxMjAsInByb3Bvc2VkX3N0YXJ0IjoxNjMzMDM2Mzg4LCJwcm9wb3NlZF9lbmQiOjE2MzMwMzk2ODgsImxvY2F0aW9uIjoiRVBGTCIsImlkIjoial9kSmhZYnpubXZNYnVMc0ZNQ2dzYlB5YjJ6Nm1vZ2VtSmFON1NWaHVVTT0ifQ==",
                    "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
                    "signature": "FFqBXhZSaKvBnTvrDNIeEYMpFKI5oIa5SAewquxIBHTTEyTIDnUgmvkwgccV9NrujPwDnRt1f4CIEqzXqhbjCw==",
                    "message_id": "txbTmVMwCDkZdoaAiEYfAKozVizZzkeMkeOlzq5qMlg=",
                    "witness_signatures": []
                }
            ]
        }
    }
}
