=== dedis/popstellar/be1-go/internal/validation/protocol/query/method/publish.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/publish.json",
    "description": "Match publish query",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "method": {
            "description": "[String] operation to be performed by the query",
            "const": "publish"
        },

        "params": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "channel": {
                    "description": "[String] name of the channel",
                    "type": "string",
                    "pattern": "^/root(/[^/]+)*$",
                    "$comment": "Note: the regex matches a \"/root\" or a \"/root/<channel>\""
                },
                "message": {
                    "description": "[Message] message to be published",
                    "$ref": "message/message.json"
                }
            },

            "required": ["channel", "message"]
        },

        "jsonrpc": {
            "$comment": "Defined by the parent, but needed here for the validation"
        },

        "id": {
            "type": "integer"
        }
    },

    "required": ["method", "params", "id", "jsonrpc"]
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/federation/federation_challenge.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/fzJSZjKf-2cbXH7kds9H8NORuuFIRLkevJlN7qQemjo=/federation",
    "message": {
      "data": "eyJvYmplY3QiOiJmZWRlcmF0aW9uIiwiYWN0aW9uIjoiY2hhbGxlbmdlIiwidmFsdWUiOiI4MmVhZGRlMmE0YmE4MzI1MThiOTBiYjkzYzg0ODBlZTFhZTE2YTkxZDVlZmU5MjgxZTkxZTJlYzExZGEwM2U0IiwidGltZXN0YW1wIjoxNzEyODU0ODc0fQ==",
      "message_id": "sD_PdryBuOr14_65h8L-e1lzdQpDWxUAngtu1uwqgEI=",
      "sender": "zXgzQaa_NpUe-v0Zk_4q8k184ohQ5nTQhBDKgncHzq4=",
      "signature": "BILYwYkT5tOBL4rCD7yvhBkhAYqRXOI3ajQ2uJ1gAk-g6nRc38vMMnlHShuNCQ3dQFXYZPn37cCFelhWGjY8Bg==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/coin/post_transaction2.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/coin",
    "message": {
      "data": "eyJvYmplY3QiOiJjb2luIiwiYWN0aW9uIjoicG9zdF90cmFuc2FjdGlvbiIsInRyYW5zYWN0aW9uIjp7InZlcnNpb24iOjEsImlucHV0cyI6W3sidHhfb3V0X2hhc2giOiJwaW8tR3VjaTFPb1NORHF3NUtGX3BqQUZBallhMjV2S2VXVm45emxrTTJvPSIsInR4X291dF9pbmRleCI6MSwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleSI6IlZIZnhUbGJNM25UbkxRdUtuS2ZzMWZHUDJjd1ZUOEtKa2Mtc1JHc18yS009Iiwic2lnIjoiLU85QkRjTUQ1VzFQWmpPSGs3Z3BwLUFDZm44U2RxMHdpcXdiTXdYQWlVOGVBS1BWb01XTFhRdzF0RTlZRjdPQlMzblVJeGxvUjhGZEhlakZfeTFpQUE9PSJ9fV0sIm91dHB1dHMiOlt7InZhbHVlIjo1MCwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleV9oYXNoIjoiNF9FeXpwVENCWWRmalMxemZMYURFS3FJS2EwPSJ9fSx7InZhbHVlIjo1MCwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleV9oYXNoIjoib3ljejhkNXp0QUZTTHpYLVVESWpRbzhpSEZJPSJ9fV0sImxvY2tfdGltZSI6MH0sInRyYW5zYWN0aW9uX2lkIjoiWTRTVm1LcTFPdG84ZmVfS1ZMUlpBV0QxLWwyWmJkb0ZnU2E4VmVlMEtSMD0ifQ==",
      "message_id": "T1oT7v-smRCHmB-czWfl5waZX2co5JLUSq9jM4dV6iU=",
      "sender": "vF3T8FXyWVxu2_HnelFu23dZKKrRbZfOXQcugPY0mr8=",
      "signature": "if-CmvJZ9mh8pNrH0Qv7wXmAM7YzT-AB-76nQz_YKjCTjQ3JRQM2W1xxUTRI7_sd202mZs_Z3GiMoOP0Zu3_Ag==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/lao/close_rollcall.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=",
    "message": {
      "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjbG9zZSIsImNsb3NlZF9hdCI6MTY4MzMxNjMyNywiYXR0ZW5kZWVzIjpbIm5BSHJmbDluTFc5T09fc1JyMXE5bWtmZEFfU19pZzUxNTZhQU15a3pBdTA9IiwiVkhmeFRsYk0zblRuTFF1S25LZnMxZkdQMmN3VlQ4S0prYy1zUkdzXzJLTT0iXSwiY2xvc2VzIjoiWkN1UW1zRkFXRE5KZVNHbHlXVDZFQ18zbWZiZVBxQlVsZzl5Rm9LYUhTND0iLCJ1cGRhdGVfaWQiOiIwWXA3c0Nad19fWFJUem9oWXZ5MXJmNkVqUTlVd0pURzNsQm5GaXBXdFZFPSJ9",
      "message_id": "fYExF6GV1hzG5dlLXKTyKnzwrOu1ArFq4DhRvoGCsMw=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "ySSXnTZQwwWSTIJCdLVA6iuaNvYlvZk_t5gECRU9PGQZt0hBfzxRvy3OJ--4_X0E3Q-jHvGUP6o2QJFgRkbUBQ==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/lao/create_rollcall.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=",
    "message": {
      "data": "eyJvYmplY3QiOiJyb2xsX2NhbGwiLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoicm9sbGNhbGwgIiwiY3JlYXRpb24iOjE2ODMzMTYyNzcsInByb3Bvc2VkX3N0YXJ0IjoxNjgzMzE2Mjc3LCJwcm9wb3NlZF9lbmQiOjE2ODMzMTk4NjAsImxvY2F0aW9uIjoiQkM0MTAiLCJkZXNjcmlwdGlvbiI6Im5vdCBhIHJvYm90IiwiaWQiOiJxUUtDWWdhbjFRLVZ4QW02RzlTUHNCQWU5OFhCYm9QWkpXdkJQbUswQ2NZPSJ9",
      "message_id": "SzErSVrALRSJmx_dY2osAbRYPcoFtcxLvHZkiNoUTAw=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "S0BpcAUBmoXUWDBk_UBYAn-OtOtm-KkTKKLo0bxufcwyjYYoTVq6YbrR5GDA9ApOw7l_8dcsUq2KhegJnA45AQ==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/tests/karate/src/test/java/data/lao/valid_lao_create_fe2.json
{
  "jsonrpc":"2.0",
  "method":"publish",
  "params":
  {
    "message":{
      "data":"eyJjcmVhdGlvbiI6MTY0ODgxOTE0OCwiaWQiOiJoTVNoM2t2a0lHMGdBcWpLQ3ZrajBQV2Eza3VHd21PdnR5SEVua2d4UzdrPSIsIm5hbWUiOiJsYW80Iiwib3JnYW5pemVyIjoiWUdaR25NUkFkS2J3MDZpX1lZczFxVDA3TlBZTEFLMGNubnpDcnNDTFE0QT0iLCJ3aXRuZXNzZXMiOltdLCJvYmplY3QiOiJsYW8iLCJhY3Rpb24iOiJjcmVhdGUifQ==",
      "message_id":"ZV_OUCYDlF2ScULlLDmjZuiqzcbujEgjcaoFmLsArpU=",
      "sender":"YGZGnMRAdKbw06i_YYs1qT07NPYLAK0cnnzCrsCLQ4A=",
      "signature":"QZMdg27-pdQKUDQMlsQY1uAiIgHtT5s29n7kUUI4cHdAGVRMNopC7wVJHvpC1j6p95RN0IqZyC-VhldE0bMgAA==",
      "witness_signatures":[]
    },
    "channel":"/root"},
    "id":1
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/federation/federation_result.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/lsWUv1bKBQ0t1DqWZTFwb0nhLsP_EtfGoXHny4hsrwA=/federation",
    "message": {
      "data": "eyJvYmplY3QiOiJmZWRlcmF0aW9uIiwiYWN0aW9uIjoicmVzdWx0Iiwic3RhdHVzIjoic3VjY2VzcyIsInB1YmxpY19rZXkiOiJVdlZpVHhvS3NCM1hWUF9jdGttT0tDSnBNV2I3ZkN6cmNiMVhEbWhOZTdRPSIsImNoYWxsZW5nZSI6eyJkYXRhIjoiZXlKdlltcGxZM1FpT2lKbVpXUmxjbUYwYVc5dUlpd2lZV04wYVc5dUlqb2lZMmhoYkd4bGJtZGxJaXdpZG1Gc2RXVWlPaUpsWW1FelpUSTBaV1pqWkRCaU5UTm1ZVFk1T1RBNFltRmtOV1F4WTJJMk9UbGtOems0TUdRNU16RXdPV1JoTUdJeVltWmtOVEF6TjJNeVl6ZzVaV1V3SWl3aWRHbHRaWE4wWVcxd0lqb3hOekV6TXpnMU5UWTRmUT09Iiwic2VuZGVyIjoielhnelFhYV9OcFVlLXYwWmtfNHE4azE4NG9oUTVuVFFoQkRLZ25jSHpxND0iLCJzaWduYXR1cmUiOiJCSUxZd1lrVDV0T0JMNHJDRDd5dmhCa2hBWXFSWE9JM2FqUTJ1SjFnQWstZzZuUmMzOHZNTW5sSFNodU5DUTNkUUZYWVpQbjM3Y0NGZWxoV0dqWThCZz09IiwibWVzc2FnZV9pZCI6InNEX1BkcnlCdU9yMTRfNjVoOEwtZTFsemRRcERXeFVBbmd0dTF1d3FnRUk9Iiwid2l0bmVzc19zaWduYXR1cmVzIjpbXX19",
      "message_id": "sD_PdryBuOr14_65h8L-e1lzdQpDWxUAngtu1uwqgEI=",
      "sender": "zXgzQaa_NpUe-v0Zk_4q8k184ohQ5nTQhBDKgncHzq4=",
      "signature": "BILYwYkT5tOBL4rCD7yvhBkhAYqRXOI3ajQ2uJ1gAk-g6nRc38vMMnlHShuNCQ3dQFXYZPn37cCFelhWGjY8Bg==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/federation/federation_expect.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/fzJSZjKf-2cbXH7kds9H8NORuuFIRLkevJlN7qQemjo=/federation",
    "message": {
      "data": "eyJvYmplY3QiOiJmZWRlcmF0aW9uIiwiYWN0aW9uIjoiZXhwZWN0IiwibGFvX2lkIjoibHNXVXYxYktCUTB0MURxV1pURndiMG5oTHNQX0V0ZkdvWEhueTRoc3J3QT0iLCJwdWJsaWNfa2V5IjoiVXZWaVR4b0tzQjNYVlBfY3RrbU9LQ0pwTVdiN2ZDenJjYjFYRG1oTmU3UT0iLCJzZXJ2ZXJfYWRkcmVzcyI6IndzczovL2V0aHouY2g6OTAwMC9zZXJ2ZXIiLCJjaGFsbGVuZ2UiOnsiZGF0YSI6ImV5SnZZbXBsWTNRaU9pSm1aV1JsY21GMGFXOXVJaXdpWVdOMGFXOXVJam9pWTJoaGJHeGxibWRsSWl3aWRtRnNkV1VpT2lKbFltRXpaVEkwWldaalpEQmlOVE5tWVRZNU9UQTRZbUZrTldReFkySTJPVGxrTnprNE1HUTVNekV3T1dSaE1HSXlZbVprTlRBek4yTXlZemc1WldVd0lpd2lkR2x0WlhOMFlXMXdJam94TnpFek16ZzFOVFk0ZlE9PSIsInNlbmRlciI6InpYZ3pRYWFfTnBVZS12MFprXzRxOGsxODRvaFE1blRRaEJES2duY0h6cTQ9Iiwic2lnbmF0dXJlIjoiQklMWXdZa1Q1dE9CTDRyQ0Q3eXZoQmtoQVlxUlhPSTNhalEydUoxZ0FrLWc2blJjMzh2TU1ubEhTaHVOQ1EzZFFGWFlaUG4zN2NDRmVsaFdHalk4Qmc9PSIsIm1lc3NhZ2VfaWQiOiJzRF9QZHJ5QnVPcjE0XzY1aDhMLWUxbHpkUXBEV3hVQW5ndHUxdXdxZ0VJPSIsIndpdG5lc3Nfc2lnbmF0dXJlcyI6W119fQ==",
      "message_id": "sD_PdryBuOr14_65h8L-e1lzdQpDWxUAngtu1uwqgEI=",
      "sender": "zXgzQaa_NpUe-v0Zk_4q8k184ohQ5nTQhBDKgncHzq4=",
      "signature": "BILYwYkT5tOBL4rCD7yvhBkhAYqRXOI3ajQ2uJ1gAk-g6nRc38vMMnlHShuNCQ3dQFXYZPn37cCFelhWGjY8Bg==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/tests/karate/src/test/java/data/rollCall/close/valid_roll_call_close_2.json
{
  "method": "publish",
  "id": 33,
  "params": {
    "channel": "/root/p_EYbHyMv6sopI5QhEXBf40MO_eNoq7V_LygBd4c9RA=",
    "message": {
      "data": "ewogICJvYmplY3QiOiAicm9sbF9jYWxsIiwKICAiYWN0aW9uIjogImNsb3NlIiwKICAidXBkYXRlX2lkIjogIklHTEIzcGlwSzBwMEc1RV93RnhlZEVrNElweU0zTDdYSVFvRnVtbWhqMFk9IiwKICAiY2xvc2VzIjogIlZTc1JyY0hvT1RRSi1uVV9WVF9GYWtpTWtlelpBODZ6MlVITlpLQ3hiTjg9IiwKICAiY2xvc2VkX2F0IjogMTYzMzA5OTEzNSwKICAiYXR0ZW5kZWVzIjogWyJNNVp5Y2hFaTVyd20yMkZqd2pOdWxqTDFxTUpXRDJzRTdvWDlmY0hOTURVPSJdCn0=",
      "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
      "signature": "ONylxgHA9cbsB_lwdfbn3iyzRd4aTpJhBMnvEKhmJF_niE_pUHdmjxDXjEwFyvo5WiH1NZXWyXG27SYEpkasCA==",
      "message_id": "ede55c05d3bdfb7a5247926d361d7844b4f4ca4efde3347dbe4460dbcaec9ad6",
      "witness_signatures": []
    }
  },
  "jsonrpc": "2.0"
}
