=== dedis/popstellar/be1-go/internal/validation/protocol/query/method/publish.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/publish.json",
    "description": "Match publish query",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "method": {
            "description": "[String] operation to be performed by the query",
            "const": "publish"
        },

        "params": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "channel": {
                    "description": "[String] name of the channel",
                    "type": "string",
                    "pattern": "^/root(/[^/]+)*$",
                    "$comment": "Note: the regex matches a \"/root\" or a \"/root/<channel>\""
                },
                "message": {
                    "description": "[Message] message to be published",
                    "$ref": "message/message.json"
                }
            },

            "required": ["channel", "message"]
        },

        "jsonrpc": {
            "$comment": "Defined by the parent, but needed here for the validation"
        },

        "id": {
            "type": "integer"
        }
    },

    "required": ["method", "params", "id", "jsonrpc"]
}

=== dedis/popstellar/tests/karate/src/test/java/data/rollCall/valid_roll_call_create_2.json
{
  "method": "publish",
  "id": 3,
  "params": {
    "channel": "/root/p_EYbHyMv6sopI5QhEXBf40MO_eNoq7V_LygBd4c9RA=",
    "message": {
      "data": "ewogICAgIm9iamVjdCI6ICJyb2xsX2NhbGwiLAogICAgImFjdGlvbiI6ICJjcmVhdGUiLAogICAgImlkIjogIlZTc1JyY0hvT1RRSi1uVV9WVF9GYWtpTWtlelpBODZ6MlVITlpLQ3hiTjg9IiwKICAgICJuYW1lIjogIlJvbGwgQ2FsbCAyIiwKICAgICJjcmVhdGlvbiI6IDE2MzMwOTg4NjMsCiAgICAicHJvcG9zZWRfc3RhcnQiOiAxNjMzMDk5MTI2LAogICAgInByb3Bvc2VkX2VuZCI6IDE2MzMwOTkxNDEsCiAgICAibG9jYXRpb24iOiAiRVBGTCBjYWZldGVyaWEiLAogICAgImRlc2NyaXB0aW9uIjogIkZvb2QgaXMgd2VsY29tZSBhbnl0aW1lISIKfQ==",
      "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
      "signature": "ONylxgHA9cbsB_lwdfbn3iyzRd4aTpJhBMnvEKhmJF_niE_pUHdmjxDXjEwFyvo5WiH1NZXWyXG27SYEpkasCA==",
      "message_id": "0c01b56210be3d7a63c18464035a9ddec58e3953286139293422b548bf36acee",
      "witness_signatures": []
    }
  },
  "jsonrpc": "2.0"
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/coin/post_transaction4.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/coin",
    "message": {
      "data": "eyJvYmplY3QiOiJjb2luIiwiYWN0aW9uIjoicG9zdF90cmFuc2FjdGlvbiIsInRyYW5zYWN0aW9uIjp7InZlcnNpb24iOjEsImlucHV0cyI6W3sidHhfb3V0X2hhc2giOiJkU3NZeDdRdzFMdXE3a1phLTV0RXU3dllIbG5qTC1jNENsbTVnZHh3ODdJPSIsInR4X291dF9pbmRleCI6MCwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleSI6Im5BSHJmbDluTFc5T09fc1JyMXE5bWtmZEFfU19pZzUxNTZhQU15a3pBdTA9Iiwic2lnIjoidjJERzVOUFREcF9UV1FGbVEwSXc1M1hqblpRUFF6YXRUaEhicmVjWUdkS2hhRkRlMEkwbU5KWlJUQ3lKOGs2MGtsNnRwaG9CMzlib0hKRkhlNHdvQVE9PSJ9fSx7InR4X291dF9oYXNoIjoiZFNzWXg3UXcxTHVxN2taYS01dEV1N3ZZSGxuakwtYzRDbG01Z2R4dzg3ST0iLCJ0eF9vdXRfaW5kZXgiOjEsInNjcmlwdCI6eyJ0eXBlIjoiUDJQS0giLCJwdWJrZXkiOiJuQUhyZmw5bkxXOU9PX3NScjFxOW1rZmRBX1NfaWc1MTU2YUFNeWt6QXUwPSIsInNpZyI6InYyREc1TlBURHBfVFdRRm1RMEl3NTNYam5aUVBRemF0VGhIYnJlY1lHZEtoYUZEZTBJMG1OSlpSVEN5SjhrNjBrbDZ0cGhvQjM5Ym9ISkZIZTR3b0FRPT0ifX0seyJ0eF9vdXRfaGFzaCI6ImRTc1l4N1F3MUx1cTdrWmEtNXRFdTd2WUhsbmpMLWM0Q2xtNWdkeHc4N0k9IiwidHhfb3V0X2luZGV4IjowLCJzY3JpcHQiOnsidHlwZSI6IlAyUEtIIiwicHVia2V5IjoibkFIcmZsOW5MVzlPT19zUnIxcTlta2ZkQV9TX2lnNTE1NmFBTXlrekF1MD0iLCJzaWciOiJ2MkRHNU5QVERwX1RXUUZtUTBJdzUzWGpuWlFQUXphdFRoSGJyZWNZR2RLaGFGRGUwSTBtTkpaUlRDeUo4azYwa2w2dHBob0IzOWJvSEpGSGU0d29BUT09In19LHsidHhfb3V0X2hhc2giOiJkU3NZeDdRdzFMdXE3a1phLTV0RXU3dllIbG5qTC1jNENsbTVnZHh3ODdJPSIsInR4X291dF9pbmRleCI6MSwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleSI6Im5BSHJmbDluTFc5T09fc1JyMXE5bWtmZEFfU19pZzUxNTZhQU15a3pBdTA9Iiwic2lnIjoidjJERzVOUFREcF9UV1FGbVEwSXc1M1hqblpRUFF6YXRUaEhicmVjWUdkS2hhRkRlMEkwbU5KWlJUQ3lKOGs2MGtsNnRwaG9CMzlib0hKRkhlNHdvQVE9PSJ9fV0sIm91dHB1dHMiOlt7InZhbHVlIjo1MCwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleV9oYXNoIjoib3ljejhkNXp0QUZTTHpYLVVESWpRbzhpSEZJPSJ9fSx7InZhbHVlIjoxMDAsInNjcmlwdCI6eyJ0eXBlIjoiUDJQS0giLCJwdWJrZXlfaGFzaCI6IjRfRXl6cFRDQllkZmpTMXpmTGFERUtxSUthMD0ifX1dLCJsb2NrX3RpbWUiOjB9LCJ0cmFuc2FjdGlvbl9pZCI6InBLOHF4X3doUktjbGoyMXFSRjlWZWJ5NnNoWk02V25rYTdwbHdPLW0zRDQ9In0=",
      "message_id": "SpexxR28mMd8GU40As8ASex44YHAH0rLsENvhj-7wJ0=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "8xBeUuLWJ58sir2CLnWXmLaxIX8xQ-H-G6Rctg_OuDH6vBRKnXX0zMvHxvwK92YPwQM1OvgcyR7WE52uj13lCw==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/social/add_chirp2.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel":  "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/social/nAHrfl9nLW9OO_sRr1q9mkfdA_S_ig5156aAMykzAu0=",
    "message": {
      "data": "eyJvYmplY3QiOiJjaGlycCIsImFjdGlvbiI6ImFkZCIsInRleHQiOiJDaGlycCAyIiwidGltZXN0YW1wIjoxNjgzMzE2MzUzfQ==",
      "message_id": "4KR6LpgzziWI8bxA2MFwyvcD7VY20-sh1fWuIY6M_Uk=",
      "sender": "nAHrfl9nLW9OO_sRr1q9mkfdA_S_ig5156aAMykzAu0=",
      "signature": "7zMIKJ1-QxVDDRSvbXuqMU2aRhi4ojH0EFo1BrmVM1f-is4V7ozhm4hMkHGJexOZnrK9GG4fyKNnoLgnCEFKAA==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/social/reactions/like_chirp1.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/social/reactions",
    "message":  {
      "data": "eyJvYmplY3QiOiJyZWFjdGlvbiIsImFjdGlvbiI6ImFkZCIsInJlYWN0aW9uX2NvZGVwb2ludCI6IvCfkY0iLCJjaGlycF9pZCI6IktyVlVMNEVXY0xzdVcxNzE5RW16SkpFZ29samtEM3Z1Nm5rN2xISEJ4eEE9IiwidGltZXN0YW1wIjoxNjgzMzE2MzU5fQ==",
      "message_id": "STC4LM2BeQMpWKLT4KlBMME00xvtMXcGxAyID_6zcos=",
      "sender": "nAHrfl9nLW9OO_sRr1q9mkfdA_S_ig5156aAMykzAu0=",
      "signature": "In663OLt7aQpi0UNOVb-535opm_jYo2GEch9gmppQmbJWRLoOVomsBcZefqV3c_kED6VXfgFa67__6FkbP4IBQ==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/social/reactions/dislike_chirp1.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/social/reactions",
    "message": {
      "data": "eyJvYmplY3QiOiJyZWFjdGlvbiIsImFjdGlvbiI6ImFkZCIsInJlYWN0aW9uX2NvZGVwb2ludCI6IvCfkY4iLCJjaGlycF9pZCI6IktyVlVMNEVXY0xzdVcxNzE5RW16SkpFZ29samtEM3Z1Nm5rN2xISEJ4eEE9IiwidGltZXN0YW1wIjoxNjgzMzE2MzU2fQ==",
      "message_id": "JQjFMIR63dUEQnAkr7z7DPRMHrPQ1xA1nEJkxcy8VBc=",
      "sender": "VHfxTlbM3nTnLQuKnKfs1fGP2cwVT8KJkc-sRGs_2KM=",
      "signature": "gZCLvRDXlNK9xwjcUrTH2OiXupXT6iWF_ZH7cJJI5U9jLEZTFErDBBTijVKmfiqqFPSJm1P7pXpW_V82cmJJCA==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/tests/karate/src/test/java/data/rollCall/open/valid_roll_call_open_2.json
{
  "method": "publish",
  "id": 32,
  "params": {
    "channel": "/root/p_EYbHyMv6sopI5QhEXBf40MO_eNoq7V_LygBd4c9RA=",
    "message": {
      "data": "ewogICJvYmplY3QiOiAicm9sbF9jYWxsIiwKICAiYWN0aW9uIjogIm9wZW4iLAogICJ1cGRhdGVfaWQiOiAia3JDSGg2T0ZXSWpTSFFpVVNyV3l4MUZWMEpwOGRlQzN6VXllbGhQRy1Zaz0iLAogICJvcGVucyI6ICJmRXZBZmR0TnJ5a2Q5TlBZbDlSZUhMWC02SVA2U0ZMS1RaSkxlR1VIWl9VPSIsCiAgIm9wZW5lZF9hdCI6IDE2MzMwOTkxMjcKfQ==",
      "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
      "signature": "ONylxgHA9cbsB_lwdfbn3iyzRd4aTpJhBMnvEKhmJF_niE_pUHdmjxDXjEwFyvo5WiH1NZXWyXG27SYEpkasCA==",
      "message_id": "3ce19889ff3355a833bb27f1748f81ace6b91d333ceb4d3c58776c011790f69f",
      "witness_signatures": []
    }
  },
  "jsonrpc": "2.0"
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/social/notify_add_chirp2.json
{
  "jsonrpc" : "2.0",
  "id" : 4,
  "method" : "publish",
  "params" : {
    "channel" : "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/social/chirps",
    "message" : {
      "data": "eyJhY3Rpb24iOiJub3RpZnlfYWRkIiwiY2hhbm5lbCI6Ii9yb290L28zbnlJSXZybURyaXdZWG5INS04Q21ZZHlaY3o0QlBOVDk5VzdkY3JrOU09L3NvY2lhbC9uQUhyZmw5bkxXOU9PX3NScjFxOW1rZmRBX1NfaWc1MTU2YUFNeWt6QXUwPSIsImNoaXJwX2lkIjoiNEtSNkxwZ3p6aVdJOGJ4QTJNRnd5dmNEN1ZZMjAtc2gxZld1SVk2TV9Vaz0iLCJvYmplY3QiOiJjaGlycCIsInRpbWVzdGFtcCI6MTY4MzMxNjM1M30=",
      "message_id": "JrYTauKi7jkMzDydI6mew6D40Ma7Yy2kcyp16WOblDw=",
      "sender": "pLGlHn5foBNLuY1Kd_s2y7-XZEAyaS4HcPVeD-VbRKE=",
      "signature": "v50rLTDXb-bxv7arZbsB9Sf-CDhjSENzzgBK_-BHXUxsM4iA1e3MV_BSVvkiqnUfqknVNDhzh4jBpgr-RvxwCA==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/election/end_election.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/iNBfwu7qLstfwC9aF0Jm9fyZGCJYqfE12PCkA5Ic5JE=",
    "message": {
      "data": "eyJvYmplY3QiOiJlbGVjdGlvbiIsImFjdGlvbiI6ImVuZCIsImxhbyI6Im8zbnlJSXZybURyaXdZWG5INS04Q21ZZHlaY3o0QlBOVDk5VzdkY3JrOU09IiwiY3JlYXRlZF9hdCI6MTY4MzMxNjQ4NCwicmVnaXN0ZXJlZF92b3RlcyI6IlNYZ0pyRWxVTDBNdXpBVzdsNmFObl9zWmJHVmYxay1yVXhfZ0E3QnlhdXc9IiwiZWxlY3Rpb24iOiJpTkJmd3U3cUxzdGZ3QzlhRjBKbTlmeVpHQ0pZcWZFMTJQQ2tBNUljNUpFPSJ9",
      "message_id": "uGw3dgqxAUQssOfPzWmTCAFarJ126PIDQ7v8GFtiSuE=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "uSv9ncI79kX15KDGZZqQYtuziL3isPBY-amVMb-iviox_plWU2-FvhLGOSb6RTChw5IoLTpIBssAeVJjvNUmDQ==",
      "witness_signatures": []
    }
  }
}
