=== dedis/popstellar/be1-go/internal/validation/protocol/query/method/publish.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/publish.json",
    "description": "Match publish query",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "method": {
            "description": "[String] operation to be performed by the query",
            "const": "publish"
        },

        "params": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "channel": {
                    "description": "[String] name of the channel",
                    "type": "string",
                    "pattern": "^/root(/[^/]+)*$",
                    "$comment": "Note: the regex matches a \"/root\" or a \"/root/<channel>\""
                },
                "message": {
                    "description": "[Message] message to be published",
                    "$ref": "message/message.json"
                }
            },

            "required": ["channel", "message"]
        },

        "jsonrpc": {
            "$comment": "Defined by the parent, but needed here for the validation"
        },

        "id": {
            "type": "integer"
        }
    },

    "required": ["method", "params", "id", "jsonrpc"]
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/social/reactions/like_chirp2.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/social/reactions",
    "message": {
      "data": "eyJvYmplY3QiOiJyZWFjdGlvbiIsImFjdGlvbiI6ImFkZCIsInJlYWN0aW9uX2NvZGVwb2ludCI6IvCfkY0iLCJjaGlycF9pZCI6IjRLUjZMcGd6emlXSThieEEyTUZ3eXZjRDdWWTIwLXNoMWZXdUlZNk1fVWs9IiwidGltZXN0YW1wIjoxNjgzMzE2MzU4fQ==",
      "message_id": "DH6FHm-x8PlQbTvav5kdWpK0gMApFJrGpCDtcI4s5JU=",
      "sender": "nAHrfl9nLW9OO_sRr1q9mkfdA_S_ig5156aAMykzAu0=",
      "signature": "6KEv9VfzNHnCQgG_gXWN5d8BJYaU4x9tYoYfJ8KQhezmKc2Bd7Qk330n9o-eA8ciWuPEyxoKUM2bO0YvSOrEBA==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/tests/karate/src/test/java/data/rollCall/valid_roll_call_create_3.json
{
  "method": "publish",
  "id": 3,
  "params": {
    "channel": "/root/p_EYbHyMv6sopI5QhEXBf40MO_eNoq7V_LygBd4c9RA=",
    "message": {
      "data": "ewogICAgIm9iamVjdCI6ICJyb2xsX2NhbGwiLAogICAgImFjdGlvbiI6ICJjcmVhdGUiLAogICAgImlkIjogInBLYlhBU1pJNk5ZYnpoRktvR2Q0SFVwSUJMRi1DTVNHQWJmZFlrZDA5UE09IiwKICAgICJuYW1lIjogIlJvbGwgQ2FsbCAzIiwKICAgICJjcmVhdGlvbiI6IDE2MzMwOTg4NjQsCiAgICAicHJvcG9zZWRfc3RhcnQiOiAxNjMzMDk5MTI3LAogICAgInByb3Bvc2VkX2VuZCI6IDE2MzMwOTkxNDgsCiAgICAibG9jYXRpb24iOiAiTGF1c2FubmUiLAogICAgImRlc2NyaXB0aW9uIjogIk5pY2UgY2l0eSEiCn0=",
      "sender": "J9fBzJV70Jk5c-i3277Uq4CmeL4t53WDfUghaK0HpeM=",
      "signature": "ONylxgHA9cbsB_lwdfbn3iyzRd4aTpJhBMnvEKhmJF_niE_pUHdmjxDXjEwFyvo5WiH1NZXWyXG27SYEpkasCA==",
      "message_id": "5cc1e2ec977aff853342199b983fb6c7f1085f91a75761a345d9cb0cf09da068",
      "witness_signatures": []
    }
  },
  "jsonrpc": "2.0"
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/coin/post_transaction1.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/coin",
    "message": {
      "data": "eyJvYmplY3QiOiJjb2luIiwiYWN0aW9uIjoicG9zdF90cmFuc2FjdGlvbiIsInRyYW5zYWN0aW9uIjp7InZlcnNpb24iOjEsImlucHV0cyI6W3sidHhfb3V0X2hhc2giOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBPSIsInR4X291dF9pbmRleCI6MCwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleSI6IlV1dnI5Y0ZlMHI3ajhmNjRhUHZyazdaNjVKdDRrdjluR3o0SFhnb3kzOFE9Iiwic2lnIjoiTzF5ZTZOcVQ3UnFxRXk2enRRN2paMm1RR2xSU05TYjEwN1A2dnRfLW9TS3pwYk9MdHZ0TzZ1eHdDUWJNb3ZVYzJGUzJWeDNzN3Y2UVNCWXlwaDdURFE9PSJ9fV0sIm91dHB1dHMiOlt7InZhbHVlIjoxMDAsInNjcmlwdCI6eyJ0eXBlIjoiUDJQS0giLCJwdWJrZXlfaGFzaCI6IjRfRXl6cFRDQllkZmpTMXpmTGFERUtxSUthMD0ifX0seyJ2YWx1ZSI6MTAwLCJzY3JpcHQiOnsidHlwZSI6IlAyUEtIIiwicHVia2V5X2hhc2giOiJveWN6OGQ1enRBRlNMelgtVURJalFvOGlIRkk9In19XSwibG9ja190aW1lIjowfSwidHJhbnNhY3Rpb25faWQiOiJwaW8tR3VjaTFPb1NORHF3NUtGX3BqQUZBallhMjV2S2VXVm45emxrTTJvPSJ9",
      "message_id": "jEHNwNC_rMHa-5NszrbCtc62hQmBXAWAnGRektF6x84=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "BSCtOJvyi-h89WeCW_baoVhLB0Gy6wJw8yGzRP97kMEzX8ZuCYaNjB_mnPClyTdVjP3Mhk19WOhdAVBOJdthBg==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/lao/create_lao.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root",
    "message": {
      "data": "eyJvYmplY3QiOiJsYW8iLCJhY3Rpb24iOiJjcmVhdGUiLCJuYW1lIjoidGVzdCIsImNyZWF0aW9uIjoxNjgzMzE2MjMyLCJvcmdhbml6ZXIiOiJVdXZyOWNGZTByN2o4ZjY0YVB2cms3WjY1SnQ0a3Y5bkd6NEhYZ295MzhRPSIsIndpdG5lc3NlcyI6W10sImlkIjoibzNueUlJdnJtRHJpd1lYbkg1LThDbVlkeVpjejRCUE5UOTlXN2Rjcms5TT0ifQ==",
      "message_id": "b1yZTpJ06PuYlPlzggt0mkaLm815-y8hwtck8tAy9FU=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "xdFqCJpI4KUwtZamrh0qGAo5w8GQNLGHmTTZY0WpN4y9IzkOtgQwL6R1ZgMHqnhQP0ji5uZjhsjcSdX7muraAg==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/election/setup_election.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/iNBfwu7qLstfwC9aF0Jm9fyZGCJYqfE12PCkA5Ic5JE=",
    "message": {
      "data": "eyJvYmplY3QiOiJlbGVjdGlvbiIsImFjdGlvbiI6InNldHVwIiwibGFvIjoibzNueUlJdnJtRHJpd1lYbkg1LThDbVlkeVpjejRCUE5UOTlXN2Rjcms5TT0iLCJ2ZXJzaW9uIjoiT1BFTl9CQUxMT1QiLCJpZCI6ImlOQmZ3dTdxTHN0ZndDOWFGMEptOWZ5WkdDSllxZkUxMlBDa0E1SWM1SkU9IiwibmFtZSI6IkVsZWN0aW9uIiwiY3JlYXRlZF9hdCI6MTY4MzMxNjQ2Niwic3RhcnRfdGltZSI6MTY4MzMxNjQ2NiwiZW5kX3RpbWUiOjE2ODMzMjAwMjYsInF1ZXN0aW9ucyI6W3siaWQiOiJxZlZPR1c0MXJsLUNPZ1lWTGJsVFZ5RTkwZkl6UXJmUUtIMjFyd3lxaDFBPSIsInF1ZXN0aW9uIjoiUXVlc3Rpb24gMSIsImJhbGxvdF9vcHRpb25zIjpbImFuc3dlciAxIiwiYW5zd2VyIDIiXSwidm90aW5nX21ldGhvZCI6IlBsdXJhbGl0eSIsIndyaXRlX2luIjpmYWxzZX0seyJpZCI6IjVTWHRiLXpOYWJzRkhQV1FuNE1TWnNFazBEcWNFRVh6ME5UTE01U1otMlk9IiwicXVlc3Rpb24iOiJRdWVzdGlvbiAyIiwiYmFsbG90X29wdGlvbnMiOlsiYW5zd2VyIDEiLCJhbnN3ZXIgMiJdLCJ2b3RpbmdfbWV0aG9kIjoiUGx1cmFsaXR5Iiwid3JpdGVfaW4iOmZhbHNlfV19",
      "message_id": "xV_G8YljVJkWzSQmyDWwBzT0g-NhQLMOuLaXtSWndzI=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "7sB1HsPav6-q05IGQVqjAPDWgQxFzMPbIno8Ayz2_9pWjwR8uuv9F7olJCkNk__qQlGiiH2-Y2RJQI_qRD0bAQ==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/lao/greet_lao.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=",
    "message": {
      "data": "eyJvYmplY3QiOiJsYW8iLCJhY3Rpb24iOiJncmVldCIsImxhbyI6Im8zbnlJSXZybURyaXdZWG5INS04Q21ZZHlaY3o0QlBOVDk5VzdkY3JrOU09IiwiZnJvbnRlbmQiOiJVdXZyOWNGZTByN2o4ZjY0YVB2cms3WjY1SnQ0a3Y5bkd6NEhYZ295MzhRPSIsImFkZHJlc3MiOiJ3czovLzEyNy4wLjAuMTo4MDAwL2NsaWVudCIsInBlZXJzIjpbXX0=",
      "message_id": "WW4XMusn_hjJngXvVPmF_4wSIqSJEuaxqflqVx_OeEE=",
      "sender": "pLGlHn5foBNLuY1Kd_s2y7-XZEAyaS4HcPVeD-VbRKE=",
      "signature": "cHx0h-WRs3P9qPp9rTQFwH_UhQ7GJWdYARNF796P39Cz83Gsrf5RYdJEmSwBZXC_diMxngHFLm48ArEDZGZaCw==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/coin/post_transaction3.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/coin",
    "message": {
      "data": "eyJvYmplY3QiOiJjb2luIiwiYWN0aW9uIjoicG9zdF90cmFuc2FjdGlvbiIsInRyYW5zYWN0aW9uIjp7InZlcnNpb24iOjEsImlucHV0cyI6W3sidHhfb3V0X2hhc2giOiJwaW8tR3VjaTFPb1NORHF3NUtGX3BqQUZBallhMjV2S2VXVm45emxrTTJvPSIsInR4X291dF9pbmRleCI6MCwic2NyaXB0Ijp7InR5cGUiOiJQMlBLSCIsInB1YmtleSI6Im5BSHJmbDluTFc5T09fc1JyMXE5bWtmZEFfU19pZzUxNTZhQU15a3pBdTA9Iiwic2lnIjoiQjNOTE82LV9EdTJ3Sy1ubFFsUU5XUm1aNG1sTVVMNTBmeFhyaWNLaHktRkMwSUV5YnR2NDhQWnVVdGZXZC1LNFo2YUcxakFUWDRodk1LNHEybi1qQUE9PSJ9fSx7InR4X291dF9oYXNoIjoiWTRTVm1LcTFPdG84ZmVfS1ZMUlpBV0QxLWwyWmJkb0ZnU2E4VmVlMEtSMD0iLCJ0eF9vdXRfaW5kZXgiOjAsInNjcmlwdCI6eyJ0eXBlIjoiUDJQS0giLCJwdWJrZXkiOiJuQUhyZmw5bkxXOU9PX3NScjFxOW1rZmRBX1NfaWc1MTU2YUFNeWt6QXUwPSIsInNpZyI6IkIzTkxPNi1fRHUyd0stbmxRbFFOV1JtWjRtbE1VTDUwZnhYcmljS2h5LUZDMElFeWJ0djQ4UFp1VXRmV2QtSzRaNmFHMWpBVFg0aHZNSzRxMm4takFBPT0ifX1dLCJvdXRwdXRzIjpbeyJ2YWx1ZSI6NTAsInNjcmlwdCI6eyJ0eXBlIjoiUDJQS0giLCJwdWJrZXlfaGFzaCI6IjRfRXl6cFRDQllkZmpTMXpmTGFERUtxSUthMD0ifX0seyJ2YWx1ZSI6MTAwLCJzY3JpcHQiOnsidHlwZSI6IlAyUEtIIiwicHVia2V5X2hhc2giOiI0X0V5enBUQ0JZZGZqUzF6ZkxhREVLcUlLYTA9In19XSwibG9ja190aW1lIjowfSwidHJhbnNhY3Rpb25faWQiOiJkU3NZeDdRdzFMdXE3a1phLTV0RXU3dllIbG5qTC1jNENsbTVnZHh3ODdJPSJ9",
      "message_id": "5hWtZA3q-b7bmCP33wZQKfYmiRXmZEAjlAV3NrDQNW4=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "B3T-FIBsymtCKn2aDhM-W37CPiOszfCziR-MXMV2swLQl46hMdcqleljjXi6cyXwYhhAU1t6dnailaLQKnJgBw==",
      "witness_signatures": []
    }
  }
}

=== dedis/popstellar/be2-scala/src/test/scala/util/examples/json/election/open_election.json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "publish",
  "params": {
    "channel": "/root/o3nyIIvrmDriwYXnH5-8CmYdyZcz4BPNT99W7dcrk9M=/iNBfwu7qLstfwC9aF0Jm9fyZGCJYqfE12PCkA5Ic5JE=",
    "message": {
      "data": "eyJvYmplY3QiOiJlbGVjdGlvbiIsImFjdGlvbiI6Im9wZW4iLCJsYW8iOiJvM255SUl2cm1Ecml3WVhuSDUtOENtWWR5WmN6NEJQTlQ5OVc3ZGNyazlNPSIsIm9wZW5lZF9hdCI6MTY4MzMxNjQ3MSwiZWxlY3Rpb24iOiJpTkJmd3U3cUxzdGZ3QzlhRjBKbTlmeVpHQ0pZcWZFMTJQQ2tBNUljNUpFPSJ9",
      "message_id": "CvPnQaEMpnJipXi21bNk8VpNubyvHYER6SRfY1C12ys=",
      "sender": "Uuvr9cFe0r7j8f64aPvrk7Z65Jt4kv9nGz4HXgoy38Q=",
      "signature": "6c3jD8s4VwIeiv3-OrSkGxAG0SfPGwwX1YO-ioYcBVPZqsR_KQCEM6cb_M_XdSMag3Z6HVAXsWsu7vBtFKNtDA==",
      "witness_signatures": []
    }
  }
}
